name: "GODOT-CI"
permissions:
  contents: write
on: [push, pull_request]


env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: plateform-toy
  PROJECT_PATH: plateform-toy

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    permissions:
        contents: write
    container:
      image: barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p .local/share/godot/export_templates
          cp -r /root/.local/share/godot/templates/${GODOT_VERSION}.stable .local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Copy Export Preset
        run: |
          cp export_presets.example.cfg export_presets.cfg
      - name: Web Build
        run: |
          mkdir -v -p build/web
          godot -v --headless --export-release "Web" build/web/index.html
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: web
          path: builds/web
          retention-days: 1
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build/web